meelorlah/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name='login'),
    url(r"logout/$",
        auth_views.LogoutView.as_view(),
        name="logout"),
    url(r"signup/$",
        views.SignUp.as_view(),
        name="signup"),
]

meelorlah/meelorlah/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/", include("groups.urls", namespace="groups")),
]

meelorlah/posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",
        views.UserPosts.as_view(), name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.PostDetail.as_view(), name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeletePost.as_view(), name="delete"),
    # url(r"delete/(?P<pk>\d+)/(?P<edited_ms
    url(r'^edit/(?P<pk>\d+)/$', views.EditPost.as_view(), name='post_edit'),
]

meelorlah/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Meelorlah Elite World</title>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'meelorlah/css/master.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Lato:100i,300,400" rel="stylesheet" type ="text/css">
  </head>
  <body>
    <header>
        {% block header %}
            {% include "nav_partial.html" %}
        {% endblock %}
        <div class="hero-text-box">
            {% block content %}
                <h1 class ="home-text">Welcome to Meelorlah Elit World!</h1>
            {% endblock %}
            <a class = "btn btn-full" href = "#">We beautify</a>
            <a class = "btn btn-ghost" href = "#">Show me more </a>
        </div>
    </header>
    {% block section %}
        {% include "sections_partial.html" %}
    {% endblock %}

    {% block footer %}
      {% include "footer_partial.html" %}
    {% endblock %}
    <script src="{% static "meelorlah/js/master.js"%}" type="text/javascript" ></script>
  </body>
</html>

meelorlah/templates/footer_partial.html
{% load static %}


<footer class="footer">
    <div class="row">
        <div class="col-6">
            <ul class="footer-nav">
                <p class="copy">
                    Copyright &copy; 2017 by MEW. All rights reserved  
                </p>    
            </ul>    

        </div>
        <div class="col-6">
            <ul class = "social-links">
                <li> <a href="https://www.facebook.com/search/top/?q=meelorlah%20elit%20world%20-%20mew" target="blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li> <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li> <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                <li> <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            </ul>               
        </div>
    </div> 
</footer>

meelorlah/templates/groups-base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Meelorlah Elite World</title>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'meelorlah/css/master.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Lato:100i,300,400" rel="stylesheet" type ="text/css">
  </head>
  <body>
    <div>
        {% block header %}
            {% include "login-nav-partial.html" %}
        {% endblock %}
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div class ="groups-footer">
            {% block footer %}
            {% include "footer_partial.html" %}
          {% endblock %}
    </div>
  </body>
  <script src="{% static "meelorlah/js/master.js"%}" type="text/javascript" ></script>
</html>

meelorlah/templates/index.html
{% extends "base.html" %}

meelorlah/templates/login-base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Meelorlah Elite World</title>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'meelorlah/css/master.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Lato:100i,300,400" rel="stylesheet" type ="text/css">
  </head>
  <body>
    <div>
        {% block header %}
            {% include "login-nav-partial.html" %}
        {% endblock %}
        <div class="content login">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div>
    <div class = "login-footer">
      {% block footer %}
        {% include "footer_partial.html" %}
      {% endblock %}
     </div>
    </div>
  </body>
  <script src="{% static "meelorlah/js/master.js"%}" type="text/javascript" ></script>
</html>

meelorlah/templates/login-nav-partial.html
{% load staticfiles %}

<nav class= "navbar navbar-inverse">
    <div class = "container">
        <div class ="row"> 
            <a class="navbar-brand mynav" href="{% url 'home' %}"><img src = "{%static 'meelorlah/img/logo.png' %}" alt="meelorlah logo" class="logo"></a>
            <div class= "container-fluid">
                <div class="navbar-header">
                    <button type= "button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>   
                </div> 
                <div class="collapse navbar-collapse" id="myNavbar">   
                <ul class= "nav navbar-nav navbar-right">
                 {% if user.is_authenticated %}
                        <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                        <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                        <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                        <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Share <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="#">Facebook</a></li>
                            <li><a href="#">Twitter</a></li>
                            <li><a href="#">Instagram</a></li>
                          </ul>
                        </li>  
                        
                  {% else %}
                        <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
                        <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                        <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
                  {% endif %}
                    </ul>  
                </div>
            </div>
        </div>
    </div>       
 </nav>  

 

meelorlah/templates/nav_partial.html
{% load staticfiles %}
<nav>
    <div class = "container">
      <div class ="row"> 
          <a class="navbar-brand mynav" href="{% url 'home' %}"><img src = "{%static 'meelorlah/img/logo.png' %}" alt="meelorlah logo" class="logo"></a>
  
          <ul class="nav nav-tabs nav-justified">
              {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                    <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                    <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Share <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Instagram</a></li>
                      </ul>
                    </li>  
                    
              {% else %}
                    <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                    <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
              {% endif %}
            </ul>
        </div>     
    </div>
  </nav>

meelorlah/templates/posts-base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Meelorlah Elite World</title>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'meelorlah/css/master.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Lato:100i,300,400" rel="stylesheet" type ="text/css">
  </head>
  <body>
    <div>
        {% block header %}
            {% include "login-nav-partial.html" %}
        {% endblock %}
        <div class="content">
            {% block post_content%}
            {% endblock %}
        </div>
    </div>
    <div class ="groups-footer">
            {% block footer %}
            {% include "footer_partial.html" %}
          {% endblock %}
    </div>
  </body>
  <script src="{% static "meelorlah/js/master.js"%}" type="text/javascript" ></script>
</html>

meelorlah/templates/sections_partial.html
{% load static %}
{% load bootstrap3 %}

<section class="section-features">  
    <div class = "row">  
        <h2> Get beauteous &mdash;  NOT inferior</h2>
        <p class = "long-copy">
            Hello, we’re MEW, your new premium full professional beauty and personal care provider service. We know you’re always busy. No time for exhaustive make up. So let us give it to you in quality and in time, we’re really good at it, we promise!
        </p>
    </div>
    <div class="row">
        <div class="col-md-4 box">
          <span class="glyphicon glyphicon-check icon-big "></span>
          <h3>Up to 365 days/year</h3>
          <p>Never worry about everyday looks again! We really mean that. Our subscription plans include up to 365 days/year coverage. You can also choose to order, Our Team is mobile and readily available.
          </p>
        </div>
        <div class="col-md-4 box"> 
          <span class=" glyphicon glyphicon-plane icon-big "></span>
          <h3>Ready in 20 minutes</h3>
          <p>You're only twenty minutes away from your ready made and super makeup provided right to your home. We work with the best creative arts in each town to ensure that you're 100% happy..</p>
        </div>
        <div class="col-md-4 box">
          <span class="glyphicon glyphicon-inbox icon-big "></span>
          <h3>Order anything</h3>
          <p>We don't limit our creativity, which means you can order whatever art you feel like. You can also choose from our products containing over 30 artistic models. It's up to you!</p>
        </div>
    </div>       
</section> 
<section class="section-costume">
    <div>
        <ul class="costume-showcase">
            <li>
                <figure class="costume-photo">
                    <img src="{% static 'meelorlah/img/img1.jpg' %}" alt="Makeup ties">
                </figure>
            </li>
            <li>
                <figure class="costume-photo">
                    <img src="{% static 'meelorlah/img/img2.jpg' %}" alt="Interns wanted">
                </figure>
            </li>
            <li>
                <figure class="costume-photo">
                    <img src="{% static 'meelorlah/img/img3.jpg' %}" alt="50years we makeup">
                </figure>
            </li>
            <li>
                <figure class="costume-photo">
                    <img src="{% static 'meelorlah/img/img4.jpg' %}"alt="Bridal head style">
                </figure>
            </li>
        </ul>
    </div>
    <div>
        <ul class="costume-showcase">
            <li>
                <figure class="costume-photo">
                    <img src="{% static 'meelorlah/img/img14.jpg' %}" alt="Beads making">
                </figure>
            </li>
            <li>
                <figure class="costume-photo">
                    <img src="{% static 'meelorlah/img/img13.jpg' %}" alt="Gele ties">
                </figure>
            </li>
            <li>
                <figure class="costume-photo">
                    <img src="{% static 'meelorlah/img/img11.jpg' %}" alt="Beads accross">
                </figure>
            </li>
            <li>
                <figure class="costume-photo">
                    <img src="{% static 'meelorlah/img/img7.jpg' %}" alt="Gele headties">
                </figure>
            </li>
        </ul>
    </div>
    <div class="row" /> <!-- Create line break using row padding and margin -->
</section>

meelorlah/templates/signup-base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Meelorlah Elite World</title>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'meelorlah/css/master.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Lato:100i,300,400" rel="stylesheet" type ="text/css">
  </head>
  <body>
    <div>
        {% block header %}
            {% include "signup-nav-partial.html" %}
        {% endblock %}
        <div class="signup-content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div>
    {% block footer %}
      {% include "footer_partial.html" %}
    {% endblock %}
    </div>
  </body>
  <script src="{% static "meelorlah/js/master.js"%}" type="text/javascript" ></script>
</html>

meelorlah/templates/subnav-partial.html
{% load staticfiles %}

<nav class= "navbar navbar-inverse">
    <div class = "container">
        <div class ="row"> 
            <a class="navbar-brand mynav" href="{% url 'home' %}"><img src = "{%static 'meelorlah/img/logo.png' %}" alt="meelorlah logo" class="logo"></a>
            <div class= "container-fluid">
                <div class="navbar-header">
                    <button type= "button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>   
                </div> 
                <div class="collapse navbar-collapse" id="myNavbar">   
                <ul class= "nav navbar-nav navbar-right">
                        <li><a href="{% url 'groups:all' %}"class="btn btn-simple-login">Groups</a></li>
                        <li><a href="{% url 'accounts:login' %}" class="btn btn-simple-login">Log in</a></li>
                        <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple-login">Sign up</a></li>
                    </ul>  
                </div>
            </div>
        </div>
    </div>       
 </nav>  

meelorlah/templates/test-base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Meelorlah Elite World</title>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'meelorlah/css/master.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Lato:100i,300,400" rel="stylesheet" type ="text/css">
  </head>
  <body>
    <div>
        {% block header %}
            {% include "login-nav-partial.html" %}
        {% endblock %}
    </div>
    <div class="content test">
        {% block content %}
        {% endblock %}
    </div>
    <div class = "footer-test">
        {% block footer %}
        {% include "footer_partial.html" %}
        {% endblock %}
    </div>
  </body>
  <script src="{% static "meelorlah/js/master.js"%}" type="text/javascript" ></script>
</html>

meelorlah/templates/test.html
{% extends "test-base.html" %}
{% block content %}
<div class="container">
  <h1 class = test>You are now logged in!</h1>
  <h2><a class = "allgroups-link" href="{% url 'groups:all'%}">Go to Groups</a></h2>
</div>

{% endblock %}

meelorlah/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}